In [1]:
#!/usr/bin/env python
import pandas as pd

df = pd.read_csv('/data/serverless-ac21/YmlStats.csv',index_col=False)
df

,YML File,Prolog File,FNs Using Roles,FN Count,Private FN Count,Public FN Count,Resource Count,Public RW Resources,Public RO Resources,Public WO Resources,...,Partial Wildcard Permissions,Permission Facts Generated,Min Facts Generated Per FN,Max Facts Generated Per FN,Avg Facts Generated Per FN,Event Triggers,S3 Triggers,IoT Triggers,Stream Msg Triggers,SNS Msg Triggers
0,/data/serverless-dataset/lingrino/infra-person...,/data/results/lingrino-infra-personal-3.pl,0,1,1,0,0,0,0,0,...,0,0,0,0,0.0,2,0,0,0,2
1,/data/serverless-dataset/nikgraf/serverless-fr...,/data/results/nikgraf-serverless-framework-cou...,0,1,0,1,1,0,0,0,...,0,1,1,1,1.0,0,0,0,0,0
2,/data/serverless-dataset/nikgraf/serverless-fr...,/data/results/nikgraf-serverless-framework-cou...,0,2,0,2,2,0,0,0,...,0,4,2,2,2.0,0,0,0,0,0
3,/data/serverless-dataset/bbilger/jrestless-exa...,/data/results/bbilger-jrestless-examples-10.pl,0,1,0,1,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
4,/data/serverless-dataset/DavidWells/serverless...,/data/results/DavidWells-serverless-workshop-1...,0,2,1,1,1,0,1,0,...,0,4,2,2,2.0,4,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,/data/serverless-dataset/bridgecrewio/checkov/...,/data/results/bridgecrewio-checkov-1049.pl,0,1,1,0,0,0,0,0,...,0,1,1,1,1.0,0,0,0,0,0
304,/data/serverless-dataset/bridgecrewio/checkov/...,/data/results/bridgecrewio-checkov-1050.pl,0,1,1,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
305,/data/serverless-dataset/bridgecrewio/checkov/...,/data/results/bridgecrewio-checkov-1051.pl,0,1,1,0,0,0,0,0,...,0,1,1,1,1.0,0,0,0,0,0
306,/data/serverless-dataset/bridgecrewio/checkov/...,/data/results/bridgecrewio-checkov-1052.pl,0,1,1,0,0,0,0,0,...,0,1,1,1,1.0,0,0,0,0,0
307,/data/serverless-dataset/bridgecrewio/checkov/...,/data/results/bridgecrewio-checkov-1054.pl,0,1,1,0,0,0,0,0,...,0,1,1,1,1.0,0,0,0,0,0

# Functions

In [2]:
print('Count of projects with X functions')
print(df.groupby(['FN Count']).size())

print('\nProjects with public functions: {}'.format(df[df['Public FN Count'] > 0].shape[0]))
print('Projects with private functions: {}'.format(df[df['Private FN Count'] > 0].shape[0]))

print('\nNumber of public functions: {}'.format(df['Public FN Count'].sum()))
print('Number of private functions: {}'.format(df['Private FN Count'].sum()))

Count of projects with X functions
FN Count
1     193
2      47
3      27
4      14
5      11
6       5
7       1
9       2
10      3
11      2
13      1
19      1
21      1
dtype: int64

Projects with public functions: 180
Projects with private functions: 162

Number of public functions: 386
Number of private functions: 253

# Number of Resources

In [3]:
print('Projects that use resources: {}'.format(df[df['Resource Count'] > 0].shape[0]))
print('Projects that use resources with public function: {}'.format(df[(df['Resource Count'] > 0) & (df['Public FN Count'] > 0)].shape[0]))
print('Projects that use Private Resources: {}'.format(df[df['Private Resources'] > 0].shape[0]))
print('Projects that use Public RO Resources: {}'.format(df[df['Public RO Resources'] > 0].shape[0]))
print('Projects that use Public WO Resources: {}'.format(df[df['Public WO Resources'] > 0].shape[0]))
print('Projects that use Public RW Resources: {}'.format(df[df['Public RW Resources'] > 0].shape[0]))

print('\nNumber of private resources: {}'.format(df['Private Resources'].sum()))
print('Number of public RO resources: {}'.format(df['Public RO Resources'].sum()))
print('Number of public WO resources: {}'.format(df['Public WO Resources'].sum()))
print('Number of public RW resources: {}'.format(df['Public RW Resources'].sum()))

print('\nCount of resources by type')
print('Total Resources used: {}'.format(df['Resource Count'].sum()))
print('dynamodb Resources: {}'.format(df['dynamodb Resources'].sum()))
print('s3 Resources: {}'.format(df['s3 Resources'].sum()))
print('sns Resources: {}'.format(df['sns Resources'].sum()))
print('ssm Resources: {}'.format(df['ssm Resources'].sum()))
print('sqs Resources: {}'.format(df['sqs Resources'].sum()))
print('sdb Resources: {}'.format(df['sdb Resources'].sum()))
print('kms Resources: {}'.format(df['kms Resources'].sum()))
print('kinesis Resources: {}'.format(df['kinesis Resources'].sum()))
print('rds Resources: {}'.format(df['rds Resources'].sum()))
print('secretsmanager Resources: {}'.format(df['secretsmanager Resources'].sum()))
print('route53 Resources: {}'.format(df['route53 Resources'].sum()))
print('apigateway Resources: {}'.format(df['apigateway Resources'].sum()))
print('event Resources: {}'.format(df['event Resources'].sum()))

print("\nCount of projects with X resources")
df.groupby(['Resource Count']).size()

Projects that use resources: 100
Projects that use resources with public function: 73
Projects that use Private Resources: 90
Projects that use Public RO Resources: 8
Projects that use Public WO Resources: 0
Projects that use Public RW Resources: 3

Number of private resources: 129
Number of public RO resources: 9
Number of public WO resources: 0
Number of public RW resources: 3

Count of resources by type
Total Resources used: 141
dynamodb Resources: 71
s3 Resources: 45
sns Resources: 4
ssm Resources: 6
sqs Resources: 5
sdb Resources: 0
kms Resources: 2
kinesis Resources: 4
rds Resources: 1
secretsmanager Resources: 1
route53 Resources: 0
apigateway Resources: 0
event Resources: 0

Count of projects with X resources

Resource Count
0    208
1     78
2     14
3      4
4      1
5      1
6      1
8      1
dtype: int64

# Policies

In [4]:
print("Projects with '*' used for permissions: {}".format(df[df['Full Wildcard Permissions'] > 0].shape[0]))
print("Projects with '*' used for resources: {}".format(df[df['Full Wildcard Resources'] > 0].shape[0]))
print("Projects with Partial Wildcard used for permissions: {}".format(df[df['Partial Wildcard Permissions'] > 0].shape[0]))
print("Projects with Partial Wildcard used for resources: {}".format(df[df['Partial Wildcard Resources'] > 0].shape[0]))

print("\nProjects using only global policies: {}".format(df[(df['Global IAM Stmts'] > 0) & (df['Max Stmts Defined Per FN'] == 0)].shape[0]))
print("Projects using only function policies: {}".format(df[(df['Global IAM Stmts'] == 0) & (df['Max Stmts Defined Per FN'] > 0)].shape[0]))
print("Projects using both global and function: {}".format(df[(df['Global IAM Stmts'] > 0) & (df['Max Stmts Defined Per FN'] > 0)].shape[0]))
# Print out the missing projects that use roles (not global policy or function level statements)
df[(df['Global IAM Stmts']== 0) & (df['Max Stmts Defined Per FN'] == 0)][['YML File', 'Prolog File', 'FNs Using Roles']]

 # TODO: min max avg number of statements on functions
 # TODO: min max avg number of statements project wide
 # TODO: min max avg number of permission facts generated

Projects with '*' used for permissions: 7
Projects with '*' used for resources: 148
Projects with Partial Wildcard used for permissions: 92
Projects with Partial Wildcard used for resources: 109

Projects using only global policies: 277
Projects using only function policies: 7
Projects using both global and function: 13

,YML File,Prolog File,FNs Using Roles
38,/data/serverless-dataset/jkrnak/serverless-lam...,/data/results/jkrnak-serverless-lambda-at-edge...,1
47,/data/serverless-dataset/tminussi/curso-nanose...,/data/results/tminussi-curso-nanoservices-190.pl,1
48,/data/serverless-dataset/tminussi/curso-nanose...,/data/results/tminussi-curso-nanoservices-191.pl,1
49,/data/serverless-dataset/tminussi/curso-nanose...,/data/results/tminussi-curso-nanoservices-192.pl,1
50,/data/serverless-dataset/tminussi/curso-nanose...,/data/results/tminussi-curso-nanoservices-193.pl,1
51,/data/serverless-dataset/tminussi/curso-nanose...,/data/results/tminussi-curso-nanoservices-194.pl,2
57,/data/serverless-dataset/phpstan/phpstan/playg...,/data/results/phpstan-phpstan-286.pl,3
84,/data/serverless-dataset/Financial-Times/ig-im...,/data/results/Financial-Times-ig-images-backen...,2
106,/data/serverless-dataset/marksteele/edge-rewri...,/data/results/marksteele-edge-rewrite-453.pl,1
107,/data/serverless-dataset/tholcman/deeplens-cha...,/data/results/tholcman-deeplens-challenge-454.pl,1
177,/data/serverless-dataset/CloudySnake/flask-cog...,/data/results/CloudySnake-flask-cognito-integr...,1

# Events

In [5]:
print('Projects using "Events" triggers: {}'.format(df[df['Event Triggers'] > 0].shape[0]))
print('Projects using S3 triggers: {}'.format(df[df['S3 Triggers'] > 0].shape[0]))
print('Projects using IoT triggers: {}'.format(df[df['IoT Triggers'] > 0].shape[0]))
print('Projects using Stream triggers: {}'.format(df[df['Stream Msg Triggers'] > 0].shape[0]))
print('Projects using SNS triggers: {}'.format(df[df['SNS Msg Triggers'] > 0].shape[0]))

print('\nCount of events by type')
print('Events: {}'.format(df['Event Triggers'].sum()))
print('S3: {}'.format(df['S3 Triggers'].sum()))
print('SNS: {}'.format(df['SNS Msg Triggers'].sum()))
print('Stream: {}'.format(df['Stream Msg Triggers'].sum()))
print('IoT: {}'.format(df['IoT Triggers'].sum()))

Projects using "Events" triggers: 86
Projects using S3 triggers: 32
Projects using IoT triggers: 0
Projects using Stream triggers: 14
Projects using SNS triggers: 13

Count of events by type
Events: 208
S3: 143
SNS: 15
Stream: 14
IoT: 0